### PR TITLE
Switch to Jest for testing

### PR DESCRIPTION
**Pull request by kaimallea**
Simply because I haven't worked with Mocha in years and am more familiar with Jest.

/cc @KenEucker

### CODE REVIEW

**Comment by KenEucker** [comment]
@kaimallea I'm down to learn Jest. Let's do this. 🚀

**Comment by KenEucker** [comment]
@kaimallea I could have included this screenshot:

Screen Shot 2021-02-26 at 1 34 14 PM

All tests are passing! There's a warning about the lockFileVersion that may be due to my setup, I will look into that.

**Comment by kaimallea** [comment]
@KenEucker nice!  re: lockFileVersion, you might need to update your copy of npm (`npm install -g npm@latest`). I'm on v7.6.0

**Comment by KenEucker** [comment]
> @KenEucker nice! re: lockFileVersion, you might need to update your copy of npm (`npm install -g npm@latest`). I'm on v7.6.0

Yup, that resolved it!

You wanna know something funny? Jest uses `request` 2.88.2. 😆 🤣 

Screen Shot 2021-02-26 at 1 41 19 PM

My quest to get `request` updated across my used npm packages continues!

**Comment by kaimallea** [comment]
LMAO 🤣

**Comment by kaimallea** [comment]
I trust that the Facebook team will fix that sooner rather than later (unless you send them a PR first hehe)

**Comment by KenEucker** [comment]
@kaimallea I did create a bug report issue just now. The underlying dependency at fault here is jsdom, and they have solid work towards the full replacement needed already finished. I think that there will come an update to these packages soon enough for us to not worry about it.

Of note: I read through all of the jsdom tickets and they have put a lot of brainpower into this problem. While node-fetch was often discussed, `got` came into the conversation within the last 6 months and would more than likely have been their choice for a drop-in replacement if someone on the team hadn't rewritten all of their testing to support node-fetch.

So I think, for now, `got` is going to be fine for this project. 

Finally, in that thread, I also found this: https://www.npmjs.com/package/@root/request

If I had known of that package before working with `got`, I probably would have used that. It was simple work for this project so replacing it once again would be easier next time around.

**Pull request merged**
