### PR TITLE
Keneucker/feature new getGalleryInfo method

### PR DESCRIPTION
**Pull request by KenEucker**
Adding the getGalleryInfo method.

This addresses an item from #63.

### CODE REVIEW

**Review by kaimallea — COMMENTED** [review]
Looks good but is missing a test. Will add a good example in the PR comment

**Comment by kaimallea** [comment]
@KenEucker If you add the following to the `handlers` array inside of `mocks/handlers.js`:

```js
  rest.get('https://api.imgur.com/3/gallery', (_req, res, ctx) => {
    const response = {
      data: {
        whatever: 'is',
        in: 'a',
        gallery: 'response'
      },
      success: true,
      status: 200,
    };
    return res(ctx.json(response));
  }),
```

Then the `getGalleryInfo` test file can just be this:

```js
const imgur = require('../lib/imgur.js');

beforeAll(() => imgur.setClientId('abc123'));

test('gallery info is returned', async () => {
  const resp = await imgur.getGalleryInfo();
  expect(resp).toMatchInlineSnapshot();
});
```

the `toMatchInlineSnapshot()` will get updated by Jest to match the mocked data, correctly testing that our code functions properly. But probably updated the mocked response to be a real gallery response and not my bad example 😅

**Comment by KenEucker** [comment]
@kaimallea regarding gallery responses. I created a test request to the `/gallery/{id}` endpoint and this is the response I got:

```
data: {
        "id":"t5LYBq1",
        "title":"Bike tag #656",
        "description":null,
        "datetime":1599888641,
        "cover":"C2cYMVy",
        "cover_width":3000,
        "cover_height":2250,
        "account_url":"Bridgeportbiker1",
        "account_id":138147231,
        "privacy":"hidden",
        "layout":"blog",
        "views":101,
        "link":"https:\/\/imgur.com\/a\/t5LYBq1",
        "ups":1,
        "downs":3,
        "points":-2,
        "score":-1,
        "is_album":true,
        "vote":null,
        "favorite":false,
        "nsfw":false,
        "section":"",
        "comment_count":2,
        "favorite_count":0,
        "topic":null,
        "topic_id":null,
        "images_count":1,
        "in_gallery":true,
        "is_ad":false,
        "tags":[],
        "ad_type":0,
        "ad_url":"",
        "in_most_viral":false,
        "include_album_ads":false,
        "images":[{
          "id":"C2cYMVy",
          "title":null,
          "description":null,
          "datetime":1599888626,
          "type":"image\/jpeg",
          "animated":false,
          "width":3000,
          "height":2250,
          "size":838051,
          "views":208,
          "bandwidth":174314608,
          "vote":null,
          "favorite":false,
          "nsfw":null,
          "section":null,
          "account_url":null,
          "account_id":null,
          "is_ad":false,
          "in_most_viral":false,
          "has_sound":false,
          "tags":[],
          "ad_type":0,
          "ad_url":"",
          "edited":"0",
          "in_gallery":false,
          "link":"https:\/\/i.imgur.com\/C2cYMVy.jpg",
          "comment_count":null,
          "favorite_count":null,
          "ups":null,
          "downs":null,
          "points":null,
          "score":null
        }],
        "ad_config": {
          "safeFlags": [
            "album",
            "in_gallery",
            "gallery",
            "page_load"
          ],
          "highRiskFlags":[],
          "unsafeFlags":[
            "sixth_mod_unsafe",
            "under_10"
          ],
          "wallUnsafeFlags":[],
          "showsAds":false},
      },
```

Do I include each of these fields in the response object?

If so, I think we need to add a data mock for both the tests and the mocks to share, instead of all of the duplicate strings that are shared between both.

**Review by kaimallea — APPROVED** [review]
nice! 🚀 

there was a merge conflict since I merged the updateInfo PR that. I was able to fix the merge conflict right in the UI

**Comment by KenEucker** [comment]
@kaimallea great to hear. I was wondering how it would handle the conflicts but assumed that it wouldn't be too hard to fit things into the right spots. I'll be sure to catch up to the current develop branch on origin after we finish this round of PRs.

**Pull request merged**
