### PR TITLE
fix: specify type in uploadBase64

### LINKED ISSUE #178: [BUG] HTTP 400 response status (also tslib dependency is unlisted)
**Describe the bug**
I'm using `imgur@1.0.0` (tried `imgur@next` too) and every time I try uploading an image (tried file and base64, on both versions), I get a Response code 400 (Bad request) error. 
Also, `tslib` is required and I had to install manually it after I installed `imgur@next`.

**To Reproduce**
```js
const imgur = require('imgur');
imgur.setClientId(process.env.IMGUR_ID)
imgur.setAPIUrl('https://api.imgur.com/3/')
```
```js
// banner.data is a base64 string
banner = JSON.parse(req.body.banner)
    imgur.uploadBase64(banner.data).then((json) => {
        console.log(json.link)
    }).catch((err) => {
        console.log(err)
    })
```
```
HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (E:\Projects\site\node-shobi\node_modules\imgur\node_modules\got\dist\source\as-promise\index.js:117:42)    
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: undefined,
  timings: {
    start: 1619280530987,
    socket: 1619280530995,
    lookup: 1619280531030,
    connect: 1619280531090,
    secureConnect: 1619280531195,
    upload: 1619280531197,
    response: 1619280531721,
    end: 1619280531731,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 8,
      dns: 35,
      tls: 105,
      request: 2,
      firstByte: 524,
      download: 10,
      total: 744
    }
  }
}
```

**Expected behavior**
It should return a 200 response status.

**Environment (please complete the following information):**
 - Library version [e.g. 1.0.0]: 1.0.0
 - OS [e.g. macOS]: Windows 10
 - NodeJS version [e.g.14.16.0]: 14.16.1

**Additional context**
As I said, I also tried it with files, tried it with `@next` and tried multiple function types. It always returned a 400 response status. 
The ID I provided is good, I checked it using [this site](https://playground.btolab.com/sandbox/qa/stackexchange/stackoverflow/17269448/index.php) and it successfully uploaded an image.

### PR DESCRIPTION
**Pull request by kaimallea**
fix #178

### CODE REVIEW

**Review by KenEucker — COMMENTED** [review]
You know, when testing this, I added type: 'base64' and I didn't see it working.

You're saying that this code works?

**Comment by kaimallea** [comment]
@KenEucker lol, yea it worked for me. makes sense, without it, it will try to upload as a normal image. uploadUrl is correctly specifying the type, so doesn't have the problem.

Screen Shot 2021-04-25 at 9 04 49 PM

**Comment by kaimallea** [comment]
hmm, removing it reintroduces the problem. and adding it fixes it.

FWIW, I'm using [npm link](https://docs.npmjs.com/cli/v7/commands/npm-link) to test in a clean repo. What's your test setup?

**Comment by KenEucker** [comment]
@kaimallea my test setup is that I ran npm install Imgur and created a index.js file with the code.

If this works for you I'm happy to approve and try to discover why it doesn't work on my machine.

**Comment by kaimallea** [comment]
ScreenFlow

**Comment by KenEucker** [comment]
@kaimallea note: this happens with imgur@next, which looks like is what you were working with, but also happens with the current v1.0.1, which is what I was modifying. Maybe there's something missing but I checked to make sure that the type field was set in the extraFormParams before making the request.

**Comment by kaimallea** [comment]
I'm on v1.0.1, the extra files in my IDE is bc I checked out the `main` branch and it git didn't know how to clean up the files from `next`.

**Comment by KenEucker** [comment]
Okay, I'll approve this commit and test it after release.

**Review by KenEucker — APPROVED** [review]

**Comment by kaimallea** [comment]
¯\_(ツ)_/¯

**Comment by KenEucker** [comment]
@kaimallea I updated my package to use the new release and it still doesn't work on my machine. I've tried with multiple base64 example image strings, no dice. I wonder why it wouldn't work on my machine, but maybe you could share your base64 string?

Screen Shot 2021-04-25 at 6 27 21 PM

**Comment by kaimallea** [comment]
@KenEucker I think something's in a bad state on your machine.

I tested on RunKit, and it appears to be fixed: https://runkit.com/kmallea/60861f4f8a720e001ad42781

**Pull request merged**
