### PR TITLE
test(handlers): break out handlers into modules for maintainability

### PR DESCRIPTION
**Pull request by kaimallea**
a single array was becoming unwieldy

### CODE REVIEW

**Comment by KenEucker** [comment]
Oof. This looks good and I'm with you. Unfortunately, the PR (#122) I just added a few minutes ago doesn't follow this convention. I can make the necessary updates for that PR to follow this convention, but we may have a conflict to resolve.

**Comment by kaimallea** [comment]
dont worry I will merge this one after yours, and fix the conflicts!

**Review by KenEucker — APPROVED** [review]

**Comment by kaimallea** [comment]
ok rebased and fixed conflicts

**Pull request merged**
